src/Entity/Delivry.php
<?php

namespace App\Entity;

use App\Repository\DelivryRepository;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;
/**
 * @ORM\Entity(repositoryClass=DelivryRepository::class)
 */
class Delivry implements JsonSerializable
{
    const TYPE = [
        0 => 'A domicile',
        1 => 'Point relais',
        2 => 'Livraison de panier en entreprise'
    ];

    const TIME_SLOT = [
        0 => '6h-7h',
        1 => '7h-8h',
        2 => '8h-9h',
        3 => '9h-10h',
        4 => '10h-11h',
        5 => '11h-12h',
        6 => '12h-13h',
        7 => '13h-14h',
        8 => '14h-15h',
        9 => '15h-16h',
        10 => '16h-17h',
        11 => '17h-18h',
        12 => '18h-19h',
        13 => '19h-20h'
    ];

    const DAY_SLOT = [
        0 => 'Lundi',
        1 => 'Mardi',
        2 => 'Mercredi',
        3 => 'Jeudi',
        4 => 'Vendredi',
        5 => 'Samedi',
        6 => 'Dimanche'
    ];


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\Column(type="integer")
     */
    private $time_slot;

    /**
     * @ORM\Column(type="integer")
     */
    private $day_slot;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="delivry", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $lat_position;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $lng_position;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $postal_code;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getTimeSlot(): ?int
    {
        return $this->time_slot;
    }

    public function setTimeSlot(int $time_slot): self
    {
        $this->time_slot = $time_slot;

        return $this;
    }

    public function getDaySlot(): ?int
    {
        return $this->day_slot;
    }

    public function setDaySlot(int $day_slot): self
    {
        $this->day_slot = $day_slot;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

 
    public function getDelivryType(): string
    {
        return self::TYPE[$this->type];
    }

    public function getDelivryTimeSlot(): string
    {
        return self::TIME_SLOT[$this->time_slot];
    }

    public function getDelivryDaySlot(): string
    {
        return self::DAY_SLOT[$this->day_slot];
    }

    public function getLatPosition(): ?float
    {
        return $this->lat_position;
    }

    public function setLatPosition(?float $lat_position): self
    {
        $this->lat_position = $lat_position;

        return $this;
    }

    public function getLngPosition(): ?float
    {
        return $this->lng_position;
    }

    public function setLngPosition(?float $lng_position): self
    {
        $this->lng_position = $lng_position;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }
    public function jsonSerialize()
    {
        $vars = get_object_vars($this);
        return $vars;
    }

}

src/Controller/PurchasesController.php
<?php

namespace App\Controller;


use App\Entity\FavoriteCart;
use App\Entity\Order;
use App\Form\FavoriteCartType;
use App\Repository\DelivryRepository;
use App\Repository\FavoriteCartRepository;
use App\Repository\OrderRepository;
use App\Service\Panier\PanierService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;


class PurchasesController extends AbstractController
{

    protected $session;
    protected $em;
    protected $repoOrder;
    protected $repoDelivry;

    protected $repoFavCart;

    public function __construct(SessionInterface $session, EntityManagerInterface $em, OrderRepository $repoOrder, DelivryRepository $repoDelivry, FavoriteCartRepository $repoFavCart)
    {
        $this->session = $session;
        $this->em = $em;
        $this->repoOrder = $repoOrder;
        $this->repoDelivry = $repoDelivry;
        $this->repoFavCart = $repoFavCart;
    }

    
    /**
     * @Route("/produits/commande", name="account_pass_to_order")
     */
    public function account_pass_to_order(PanierService $panierService, Request $request): Response
    {
        $paypal_client_id = $_ENV['PAYPAL_CLIENT_ID'];

        $user = $this->getUser();

        $myDelivryInfo = $this->repoDelivry->findOneBy(['user' => $user]);
        $myLastFavCart = $this->repoFavCart->findBy(['user' =>  $user], ['id'=>'DESC'],1,0);
        if (empty($myLastFavCart)) {
            $myLastFavCart = $myLastFavCart;
        } else {
            $myLastFavCart = $this->repoFavCart->findBy(['user' =>  $user], ['id'=>'DESC'],1,0)['0'];
        }
        
        $itemsInTab = $panierService->putItemsIntoArray();

        $favoriteCart = new FavoriteCart();
        $currentCart = $this->session->get('panier', []);

        $formFavCart = $this->createForm(FavoriteCartType::class, $favoriteCart);
        $formFavCart->handleRequest($request);

        if ($formFavCart->isSubmitted() && $formFavCart->isValid()) {
            $favoriteCart->setUser($this->getUser());
            $favoriteCart->setCart($currentCart);
            $this->em->persist($favoriteCart);
            $this->em->flush();
            return $this->redirectToRoute('account_pass_to_order', ['cart' => 'saved']);;
        }

        return $this->render('purchases/order.html.twig', [
            'items' => $panierService->getFullcart(),
            'total' => $panierService->getTotal(),
            'allQuantityItem' => $panierService->allQuantityItem(),
            'myDelivryInfo' => $myDelivryInfo,
            'myLastFavCart' => $myLastFavCart,
            'itemsInTab' => $itemsInTab,
            'formFavCart' => $formFavCart->createView(),
            'paypal_client_id' => $paypal_client_id,
        ]);
    }

    /**
     * @Route("/account/order/step/one", name="account_order_step_one")
     */
    public function account_order_step_one(PanierService $panierService, Request $request): Response
    {
        $user = $this->getUser();
        $myDelivryInfo = $this->repoDelivry->findOneBy(['user' => $user]);
        $myLastFavCart = $this->repoFavCart->findBy(['user' =>  $user], ['id'=>'DESC'],1,0);
        if (empty($myLastFavCart)) {
            $myLastFavCart = $myLastFavCart;
        } else {
            $myLastFavCart = $this->repoFavCart->findBy(['user' =>  $user], ['id'=>'DESC'],1,0)['0'];
        }
        $itemsInTab = $panierService->putItemsIntoArray();

        // Gestion modal : Favorite cart 
        $favoriteCart = new FavoriteCart();
        $currentCart = $this->session->get('panier', []);

        $formFavCart = $this->createForm(FavoriteCartType::class, $favoriteCart);
        $formFavCart->handleRequest($request);

        if ($formFavCart->isSubmitted() && $formFavCart->isValid()) {
            $favoriteCart->setUser($this->getUser());
            $favoriteCart->setCart($currentCart);
            $this->em->persist($favoriteCart);
            $this->em->flush();
            return $this->redirectToRoute('account_order_step_one', ['cart' => 'saved']);;
        }

        return $this->render('purchases/order_step/order_step_one.html.twig', [
            'items' => $panierService->getFullcart(),
            'total' => $panierService->getTotal(),
            'allQuantityItem' => $panierService->allQuantityItem(),
            'myDelivryInfo' => $myDelivryInfo,
            'myLastFavCart' => $myLastFavCart,
            'itemsInTab' => $itemsInTab,
            'formFavCart' => $formFavCart->createView(),
        ]);
    }


    /**
     * @Route("/account/order/step/two", name="account_order_step_two")
     */
    public function account_order_step_two(): Response
    {
        if (count($this->session->get('panier')) < 1) {
           return $this->redirectToRoute("account_order_step_one", ['error' => 'empty_cart']);
        }

        // lorsque l'étape 2 est visité, on stocke une variable dans la session pour dire qu'il est déjà passé
        $delivry = $this->session->get('delivry', []);
        $delivry['delivry_passed'] = 1;
        $this->session->set('delivry', $delivry);
        
        $user = $this->getUser();
        $myDelivryInfo = $this->repoDelivry->findOneBy(['user' => $user]);

        return $this->render('purchases/order_step/order_step_two.html.twig', [
            'myDelivryInfo' => $myDelivryInfo
        ]);
    }

    /**
     * @Route("/account/order/step/three", name="account_order_step_three")
     */
    public function account_order_step_three(PanierService $panierService): Response
    {
        if ($_ENV['PAYPAL_ENV'] == 'sandbox')  {
            $paypal_client_id = $_ENV['PAYPAL_SANDBOX_CLIENT_ID'];
            $paypal_env = 'sandbox';
        } else {
            $paypal_client_id = $_ENV['PAYPAL_CLIENT_ID'];
            $paypal_env = 'live';
        }


        $user = $this->getUser();
        if (is_null($this->session->get('panier'))){
            return  $this->redirectToRoute("account_order_step_one", ['error' => 'empty_cart']);
        }else if ($user->getDelivry() == null) {
            return  $this->redirectToRoute("account_order_step_two", ['error' => 'empty_delivry']);
        }

        $paypal_client_id = $_ENV['PAYPAL_CLIENT_ID'];

        return $this->render('purchases/order_step/order_step_three.html.twig', [
            'items' => $panierService->getFullcart(),
            'total' => $panierService->getTotal(),
            'paypal_client_id' => $paypal_client_id,
            'paypal_env' => $paypal_env
        ]);
    }
    
    /**
     * @Route("/account/order/show", name="account_order_show")
     */
    public function account_order_show(): Response
    {
        $user = $this->getUser();
        $myOrders = $this->repoOrder->findBy(['user' => $user]);

        return $this->render('purchases/show_my_orders.html.twig', [
            'myOrders' => $myOrders
        ]);
    }

    /**
     * @Route("/account/order/{order}/cart/show", name="account_order_cart_show")
     */
    public function account_order_cart_show(Order $order, PanierService $panierService): Response
    {
        $cart = $order->getCart();
        
        return $this->render('purchases/show_cart_in_order_history.html.twig', [
            'cart' => $order->getCart(),
            'items' => $panierService->getFullFavoriteCart($cart),
            'total' => $panierService->getTotalPriceFavoriteCart($cart) ,
            'allQuantityItem' => $panierService->allQuantityItemInFavoriteCart($cart)
        ]);
    }

}

templates/purchases/order_step/order_step_one.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Stripe étape 1
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="/assets/css/order_stepper.css">
    <style>
        #header{
            position: relative;
            margin-bottom: 100px;
        }

        body{
        	background-image: url('/biolife/assets/images/home-01/main-slide-01.jpg');
        }

        .fa-shopping-cart{
            color: #4CAF50;
            margin-top: -61px;    
            margin-right: 33px;
        }

        
    </style>
{% endblock %}


{% block body %}

    <div class="content">  
        {% include "partials/_order_stepper_progress_bar.html.twig" %}

        <div class="container bg-glass2 my-5">
            <!-- Etape 1 : Mon panier  -->
            <div id="step-1">
                <div class="container bg-white panier_body shadow-lg p-3 mb-5 bradius-3rem " style="overflow-x:auto;">
                    <div class="d-flex text-white justify-content-center my-3">
                        <h1 class="font-bg-stylized-1">
                            1- Mon panier
                            {% if myLastFavCart is empty or myLastFavCart.cart != itemsInTab %}
                                <i class="far fa-heart d-inline " type="button" data-bs-toggle="modal" data-bs-target="#modal-favorite-cart"></i>
                            {% elseif myLastFavCart and myLastFavCart.cart == itemsInTab %}
                                <form method="post" action="{{path('favorite_cart_delete', {cart: myLastFavCart.id} )}}" style="display: inline-block;" onsubmit="return confirm('Enleve le panier favori ?')">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ app.user.id) }}">
                                    <button style="background-color: unset; border: none;"><i class="fas fa-heart d-inline"></i></button>
                                </form>
                            {% endif %}
                        </h1>
                    </div>
                    <div class="content-step-1" >
                        <a href="{{path('all_products')}}">
                            <i class="fas fa-shopping-cart fa-2x float-end"></i>
                        </a>
                        {% include "partials/_cart.html.twig" %}
                    </div>
                </div>

            </div>
            <a href="{{ path('account_order_step_two') }}" class="button button1-inverse" style="float: right;">Suivant <i class="fas fa-arrow-circle-right"></i></a>
        </div>

    </div>

    <!-- Modal : Favorite cart  -->  
    {{ form_start(formFavCart) }}
    <div class="modal" id="modal-favorite-cart" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" >
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Enregistrement du panier</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Nom:</label>
                        {{ form_widget(formFavCart.name) }}
                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">Description:</label>
                        {{ form_widget(formFavCart.description) }}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Enregistrer le panier</button>
                </div>
            </div>
        </div>
    </div>
    {{ form_end(formFavCart) }}
{% endblock %}

templates/purchases/order_step/order_step_two.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Stripe étape 2
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin="" />
    <link rel="stylesheet" href="/assets/css/order_stepper.css">
    <style>
    	#detailsMap{
			height: 300px;
		}

        .footer-btn{
            display: flex;
            justify-content: space-around;
            align-items: center;
            flex-wrap: wrap;
        }
    </style>
{% endblock %}


{% block body %}
<body class="biolife-body">
	<div class="page-contain">
        <!-- Image bannière  -->
        <div class="banner-media-layout-01"></div>

        <div class="text-content3">   
            {% include "partials/_order_stepper_progress_bar.html.twig" %}

            <div class="container bg-glass2 my-5">
                <!-- Etape 2 : Livraison  -->
                <div id="step-2">
                    <div class="container">
                        <div id="delivry-choice" class="shadow-lg p-3 mb-5 bg-body rounded">
                            <div class="d-flex text-white justify-content-center my-3">
                                <h1 class="font-bg-stylized-1">
                                    2- Livraison <a href="{{path('account_delivry_edit')}}" class="text-white"><i class="fas fa-edit"></i></a>
                                </h1>
                            </div>
                            <div id="delivry-choice-body">
                                {% if app.user.delivry %}
                                    <table class="table">
                                        <thead>
                                            <tr class="h4">
                                            <th scope="col">Type</th>
                                            <th scope="col" class="text-center">Créneaux</th>
                                            <th scope="col" class="text-center">Jour</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                            <th> <h2> {{ myDelivryInfo.delivryType }} </h2> </th>
                                            <td> <h2> {{ myDelivryInfo.delivryTimeSlot }} </h2></td>
                                            <td> <h2> {{ myDelivryInfo.delivryDaySlot }} </h2> </td>
                                            </tr>
                                        </tbody>
                                    </table>

                                    <!-- Map layer -->
                                    <div class="d-flex text-white justify-content-center mt5-3">
                                        <h1 class="font-bg-stylized-1"> -- Position -- </h1>
                                    </div>
                                    <div id="detailsMap"></div>
                                {% else %}            
                                    <a href="{{path('account_delivry_edit')}}" class="btn btn-primary">Definir</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            <div>
            
            <div class="footer-btn">    
                <a href="{{ path('account_order_step_one') }}" class="button button1" ><i class="fas fa-arrow-circle-left"></i> Précédent</a>

                <a href="{{ path('account_order_step_three') }}" class="button button1-inverse" >Suivant <i class="fas fa-arrow-circle-right"></i></a>
            </div>

        </div>
    </div>
</body>

{% endblock %}



{% block javascripts %}
	<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
	<script>
		let map ;
		let marqueur ;
		let geoJSON ;
		let myPosition = [{{app.user.delivry.latPosition}}, {{app.user.delivry.lngPosition}}];

		window.onload = () => {
			map = L.map('detailsMap').setView(myPosition, 11);
            map.scrollWheelZoom.disable();

			L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
				attribution: 'Map data &copy; <a href="https://osm.org/copyright">OpenStreetMap</a> ODbL - rendu <a href="https://www.openstreetmap.fr/">OSM France</a>',
				minZoom: 1,
				maxZoom: 20
			}).addTo(map);
			
			// On dessine le marqueur si l'utilisateur a déjà les coordéonnés
			{% if app.user.delivry and app.user.delivry.latPosition and app.user.delivry.lngPosition %}
				let popup = L.popup()
					.setLatLng(myPosition)
					.setContent('<p>Votre point de livraison </p>')
					.openOn(map)
				;
				marqueur = L.marker(myPosition);
				marqueur.addTo(map);
				map.setView(myPosition, 11)
				marqueur.bindPopup(popup).openPopup();
			{% endif %}
        }
	</script>
{% endblock %}